package io.medatarun.auth.domain.oidc

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * All parameters are optional since they come from query string.
 *
 * We will verify in our process validity
 */
@Serializable
data class OidcAuthorizeRequest(
    /**
     * Shall only be "code", we don't support "token"
     */
    @SerialName("response_type")
    val responseType: String?,
    /**
     * Client id, ignored for us, we are not a real OIDC
     */
    @SerialName("client_id")
    val clientId: String?,
    /**
     * Where we need to redirect user after successful login (the client URI)
     */
    @SerialName("redirect_uri")
    val redirectUri: String?,
    /**
     * Shall be only "openid"
     */
    @SerialName("scope")
    val scope: String?,
    /**
     * Data we need to send back with redirect_uri
     */
    @SerialName("state")
    val state: String?,
    /**
     *
     */
    @SerialName("code_challenge")
    val codeChallenge: String?,
    /**
     * We support only "S256"
     */
    @SerialName("code_challenge_method")
    val codeChallengeMethod: String?,

    /**
     * Number used once, generated by some clients that need to be on claims on response
     */
    @SerialName("nonce")
    val nonce: String?


)



