export const ActionUILocations = {
  none: "none",
  entity: "entity",
  entity_attribute: "entity.attribute",
  entity_attributes: "entity.attributes",
  entity_relationships: "entity.relationships",
  global: "global",
  hidden: "hidden",
  model_entities: "model.entities",
  model_overview: "model.overview",
  model_relationships: "model.relationships",
  model_types: "model.types",
  models: "models",
  preferences: "preferences",
  relationship: "relationship",
  relationship_attribute: "relationship.attribute",
  relationship_attributes: "relationship.attributes",
  relationship_roles: "relationship.roles",
  relationship_role: "relationship.role",
  tag_local_detail: "tag_local_detail",
  tag_local_list: "tag_local_list",
  tag_global_detail: "tag_global_detail",
  tag_group_detail: "tag_group_detail",
  tag_group_list: "tag_group_list",
  tag_global_list: "tag_global_list",
  type: "type",
} as const;

export type ActionUILocation =
  (typeof ActionUILocations)[keyof typeof ActionUILocations];
