export const ActionUILocations = {
  none: "none",
  admin_database_drivers: "admin_database_drivers",
  auth_actor: "auth_actor",
  auth_actor_role: "auth_actor_role",
  auth_actor_roles: "auth_actor_roles",
  auth_actors: "auth_actors",
  auth_role_permission: "auth_role.permission",
  auth_role_permissions: "auth_role.permissions",
  auth_role: "auth_role",
  auth_roles: "auth_roles",
  entity: "entity",
  entity_attribute: "entity.attribute",
  entity_attributes: "entity.attributes",
  entity_relationships: "entity.relationships",
  global: "global",
  hidden: "hidden",
  model_entities: "model.entities",
  model_overview: "model.overview",
  model_relationships: "model.relationships",
  model_types: "model.types",
  models: "models",
  preferences: "preferences",
  relationship: "relationship",
  relationship_attribute: "relationship.attribute",
  relationship_attributes: "relationship.attributes",
  relationship_roles: "relationship.roles",
  relationship_role: "relationship.role",
  tag_local_detail: "tag_local_detail",
  tag_local_list: "tag_local_list",
  tag_global_detail: "tag_global_detail",
  tag_group_detail: "tag_group_detail",
  tag_group_list: "tag_group_list",
  tag_global_list: "tag_global_list",
  type: "type",
  user: "user",
  users: "users",
} as const;

export type ActionUILocation =
  (typeof ActionUILocations)[keyof typeof ActionUILocations];
